### ISSUE TITLE
Linux: fail to link libjawt

### ISSUE THREAD

**Issue by jomority** [lectureStudio/stylus#1]
**Describe the bug**
When building on Linux (Arch) with `mvn install`, I get the error `/usr/bin/ld: cannot find -ljawt`.

**To Reproduce**
1. Install jdk, maven and dependencies (base-devel, libx11, libxi, libxfixes)
2. Run `mvn install` in this repository

**Expected behavior**
The build should be successful: `[INFO] BUILD SUCCESS`

**Solution**
Symbolic linking `libjawt.so` from the jdk folder to `/usr/lib/`, for example with `ln -s /usr/lib/jvm/java-16-adoptopenjdk/lib/libjawt.so /usr/lib/`.
Maybe this could be mentioned in the build notes, so other people don't fall for the same problem?

**Comment by maxkratz** [comment]
I can confirm this issue on Ubuntu 20.04 (focal).

I've used AdoptOpenJDK 14 and the following link resolved the issue:
`$ ln -s /opt/java/jdk-14.0.2+12/lib/libjawt.so /usr/lib/libjawt.so`

> Maybe this could be mentioned in the build notes, so other people don't fall for the same problem?

Sounds like a good idea to me!

**Comment by devopvoid** [comment]
Hi @jomority @maxkratz,
if you build the library that way, what happens when you:
1.  remove the symbolic link to libjawt.so
2. build lectureStudio, if you haven't
3. start lecturePresenter
4. open whiteboard and paint something

?

**Comment by devopvoid** [comment]
This really depends on the individual JDK setup. There is no static version of libjawt. Thus, you may get a runtime error in the application that is trying to load the stylus library.

I have added this troubleshooting point to the README.

Thanks for reporting!

**Comment by maxkratz** [comment]
I'm not sure if I understood the steps correctly. Here is what I did:
1. Built `avdev` and `stylus` **with** the linked `libjawt.so` in `/usr/lib/`.
1. Removed the link.
1. Built `lectureStudio`.

Afterwards I launched my compiled `lecturePresenter` and I got the following error:
```
~/gits/lectureStudio/release/lectureStudio-4.3.3-linux-x86_64/bin -> ./lecturePresenter 
SwixML 2.6
./lecturePresenter: symbol lookup error: /tmp/libstylus3192180862816800901.so: undefined symbol: JAWT_GetAWT
```

Is this the runtime error you mentioned? If I got it right this is the same error as with the pre-compiled version mentioned in https://github.com/lectureStudio/lectureStudio/issues/7.

**Comment by devopvoid** [comment]
That's what I meant. I have to restore my working Linux setup where the jawt library was linked correctly. Will get back at you once done, so you could maybe test it then.

**Comment by devopvoid** [comment]
@jomority @maxkratz,
building this library is not necessary any more (same for avdev from the other repo), unless you want to improve it and publish new releases. I rebuild and published it to the central repository.

On occasion, please update, rebuild and test lectureStudio with your mouse or digital pen.
